/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LogEntry = IDL.Record({
  'id' : IDL.Nat,
  'role' : IDL.Text,
  'message' : IDL.Text,
  'flightPhase' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const FlightSession = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'destination' : IDL.Text,
  'entries' : IDL.Vec(LogEntry),
  'phase' : IDL.Text,
});
export const FlightSessionSummary = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'destination' : IDL.Text,
  'phase' : IDL.Text,
});

export const idlService = IDL.Service({
  'addLogEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getCurrentSession' : IDL.Func([], [IDL.Opt(FlightSession)], ['query']),
  'getFlightSessionSummaries' : IDL.Func(
      [],
      [IDL.Vec(FlightSessionSummary)],
      ['query'],
    ),
  'getLogEntries' : IDL.Func([IDL.Nat], [IDL.Vec(LogEntry)], ['query']),
  'startFlightSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateFlightPhase' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LogEntry = IDL.Record({
    'id' : IDL.Nat,
    'role' : IDL.Text,
    'message' : IDL.Text,
    'flightPhase' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const FlightSession = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'destination' : IDL.Text,
    'entries' : IDL.Vec(LogEntry),
    'phase' : IDL.Text,
  });
  const FlightSessionSummary = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'destination' : IDL.Text,
    'phase' : IDL.Text,
  });
  
  return IDL.Service({
    'addLogEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getCurrentSession' : IDL.Func([], [IDL.Opt(FlightSession)], ['query']),
    'getFlightSessionSummaries' : IDL.Func(
        [],
        [IDL.Vec(FlightSessionSummary)],
        ['query'],
      ),
    'getLogEntries' : IDL.Func([IDL.Nat], [IDL.Vec(LogEntry)], ['query']),
    'startFlightSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'updateFlightPhase' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };