/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FlightSession {
  'id' : bigint,
  'startTime' : bigint,
  'destination' : string,
  'entries' : Array<LogEntry>,
  'phase' : string,
}
export interface FlightSessionSummary {
  'id' : bigint,
  'startTime' : bigint,
  'destination' : string,
  'phase' : string,
}
export interface LogEntry {
  'id' : bigint,
  'role' : string,
  'message' : string,
  'flightPhase' : string,
  'timestamp' : bigint,
}
export interface _SERVICE {
  'addLogEntry' : ActorMethod<[bigint, string, string, string], bigint>,
  'getCurrentSession' : ActorMethod<[], [] | [FlightSession]>,
  'getFlightSessionSummaries' : ActorMethod<[], Array<FlightSessionSummary>>,
  'getLogEntries' : ActorMethod<[bigint], Array<LogEntry>>,
  'startFlightSession' : ActorMethod<[string, string], bigint>,
  'updateFlightPhase' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];